version: "3.8"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: scores
      DB_USER: postgres
      DB_PASSWORD: Soch@2608
      DB_HOST: db
      DB_PORT: 5432
    networks:
      - app-network

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: scores
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Soch@2608
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
