# Generated by Django 4.2.2 on 2025-01-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entered_text', models.TextField()),
                ('education_score', models.FloatField()),
                ('toxicity_score_normal', models.FloatField()),
                ('toxicity_score_toxic', models.FloatField()),
            ],
        ),
    ]
